# Generated by Django 5.0.6 on 2024-05-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Resume', models.FileField(upload_to='')),
                ('Photo', models.ImageField(upload_to='')),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
